In [1]:
import plotly
import plotly.plotly     as     py
import plotly.graph_objs as     go
import pandas            as     pd
from   config            import plotly_id, plotly_key

plotly.tools.set_credentials_file(username=plotly_id, api_key=plotly_key)

In [2]:
medals = pd.read_pickle('../dat/medals.pkl')
medals.head()

,Year,Summer,Games,Host,NOC,Region,Athletes,Females,Sports,Events,Medals,Golds,Silvers,Bronzes
0,1896,1,1896 Summer,0,AUS,Australia,5,0,2,5,3,2,0,1
1,1896,1,1896 Summer,0,AUT,Austria,8,0,3,8,5,2,1,2
2,1896,1,1896 Summer,0,DEN,Denmark,15,0,5,12,6,1,2,3
3,1896,1,1896 Summer,0,FRA,France,26,0,6,18,11,5,4,2
4,1896,1,1896 Summer,0,GBR,UK,25,0,7,19,9,3,3,3

In [3]:
rio_2016_medals = medals[medals['Games'] == '2016 Summer']
rio_2016_medals.head()

,Year,Summer,Games,Host,NOC,Region,Athletes,Females,Sports,Events,Medals,Golds,Silvers,Bronzes
3615,2016,1,2016 Summer,0,AFG,Afghanistan,3,1,2,3,0,0,0,0
3616,2016,1,2016 Summer,0,ALB,Albania,6,3,3,6,0,0,0,0
3617,2016,1,2016 Summer,0,ALG,Algeria,74,13,13,48,2,0,2,0
3618,2016,1,2016 Summer,0,AND,Andorra,4,2,4,4,0,0,0,0
3619,2016,1,2016 Summer,0,ANG,Angola,26,18,7,10,0,0,0,0

In [4]:
hover_text = []
color_range = []
for index, row in rio_2016_medals.iterrows():
    hover_text.append(('Games: {games}<br>'+
                       'Host: {host}<br>'+
                       'Nation: {noc}<br>'+
                       'Region: {region}<br>'+
                       'Athletes: {athletes}<br>'+
                       'Females: {females}<br>'+
                       'Sports: {sports}<br>'+
                       'Events: {events}<br>'+
                       'Medals: {medals}<br>'+
                       'Golds: {golds}<br>'+
                       'Silvers: {silvers}<br>'+
                       'Bronzes: {bronzes}').format(games    = row['Games'],
                                                    host     = row['Host'],
                                                    noc      = row['NOC'],
                                                    region   = row['Region'],
                                                    athletes = row['Athletes'],
                                                    females  = row['Females'],
                                                    sports   = row['Sports'],
                                                    events   = row['Events'],
                                                    medals   = row['Medals'],
                                                    golds    = row['Golds'],
                                                    silvers  = row['Silvers'],
                                                    bronzes  = row['Bronzes']))
    color_range.append(max(row['Athletes'],100))

trace0 = go.Scatter(
    x      = rio_2016_medals['Events'],
    y      = rio_2016_medals['Medals'],
    text   = hover_text,
    mode   = 'markers',
    marker = dict(
#        size          = rio_2016_medals['Athletes'],
        color         = color_range,
        showscale     = True,
        reversescale  = True,
        colorscale    = 'RdBu',
        colorbar      = dict(
                title = 'Total<br>Athletes'
            )
    )
)

data      = [trace0]
layout    = go.Layout(
    title = 'Medal Table of the Rio 2016 Summer Olympic Games',
    xaxis = dict(
        title         = 'Total Number of Events Participated',
        gridcolor     = 'rgb(255, 255, 255)',
        zerolinewidth = 1,
        ticklen       = 5,
        gridwidth     = 2,
    ),
    yaxis = dict(
        title         = 'Total Number of Medals Won',
        gridcolor     = 'rgb(255, 255, 255)',
        zerolinewidth = 1,
        ticklen       = 5,
        gridwidth     = 2,
    ),
    paper_bgcolor = 'rgb(243, 243, 243)',
    plot_bgcolor  = 'rgb(243, 243, 243)',
)

fig = go.Figure(data = data, layout = layout)
py.iplot(fig, filename = 'rio-2016-olympic-medals')

/anaconda3/lib/python3.7/site-packages/IPython/core/display.py:689: UserWarning:

Consider using IPython.display.IFrame instead